# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NocCPwT4O2LHBHzPWLw9Cl1SBnAr2SlB
"""

!pip install -q flask pyngrok pandas

from flask import Flask, request, send_file
from pyngrok import ngrok
import pandas as pd
import os

app = Flask(__name__)

CSV_FILE = "laptop_results.csv"


# ============================================================
# STATIC LAPTOP DATA FOR DEMONSTRATION
# ============================================================

laptops = [

    {
        "title": "Dell Inspiron 15",
        "brand": "Dell",
        "price": "₹55,990",
        "processor": "Intel Core i5",
        "ram": "16 GB",
        "storage": "512 GB SSD",
        "rating": "4.4/5"
    },

    {
        "title": "Dell XPS 13",
        "brand": "Dell",
        "price": "₹89,990",
        "processor": "Intel Core i7",
        "ram": "16 GB",
        "storage": "512 GB SSD",
        "rating": "4.6/5"
    },

    {
        "title": "Dell Vostro 15",
        "brand": "Dell",
        "price": "₹62,490",
        "processor": "Intel Core i5",
        "ram": "16 GB",
        "storage": "512 GB SSD",
        "rating": "4.3/5"
    },

    {
        "title": "Lenovo IdeaPad Slim 3",
        "brand": "Lenovo",
        "price": "₹48,990",
        "processor": "Intel Core i5",
        "ram": "16 GB",
        "storage": "512 GB SSD",
        "rating": "4.4/5"
    },

    {
        "title": "Lenovo ThinkPad E14",
        "brand": "Lenovo",
        "price": "₹67,990",
        "processor": "Intel Core i5",
        "ram": "16 GB",
        "storage": "512 GB SSD",
        "rating": "4.5/5"
    },

    {
        "title": "Lenovo Legion 5",
        "brand": "Lenovo",
        "price": "₹94,990",
        "processor": "AMD Ryzen 7",
        "ram": "16 GB",
        "storage": "1 TB SSD",
        "rating": "4.7/5"
    },

    {
        "title": "HP Pavilion 15",
        "brand": "HP",
        "price": "₹59,990",
        "processor": "Intel Core i5",
        "ram": "16 GB",
        "storage": "512 GB SSD",
        "rating": "4.3/5"
    },

    {
        "title": "HP Victus Gaming",
        "brand": "HP",
        "price": "₹79,990",
        "processor": "AMD Ryzen 5",
        "ram": "16 GB",
        "storage": "512 GB SSD",
        "rating": "4.5/5"
    },

    {
        "title": "Acer Aspire 5",
        "brand": "Acer",
        "price": "₹52,990",
        "processor": "Intel Core i5",
        "ram": "16 GB",
        "storage": "512 GB SSD",
        "rating": "4.2/5"
    },

    {
        "title": "Acer Nitro V Gaming",
        "brand": "Acer",
        "price": "₹72,990",
        "processor": "Intel Core i5",
        "ram": "16 GB",
        "storage": "512 GB SSD",
        "rating": "4.5/5"
    },

    {
        "title": "ASUS Vivobook 15",
        "brand": "ASUS",
        "price": "₹54,990",
        "processor": "Intel Core i5",
        "ram": "16 GB",
        "storage": "512 GB SSD",
        "rating": "4.4/5"
    },

    {
        "title": "ASUS ROG Strix G16",
        "brand": "ASUS",
        "price": "₹99,990",
        "processor": "Intel Core i7",
        "ram": "16 GB",
        "storage": "1 TB SSD",
        "rating": "4.7/5"
    }

]


# ============================================================
# HOME PAGE
# ============================================================

@app.route("/")
def home():

    return """
    <!DOCTYPE html>

    <html>

    <head>

        <title>Laptop Web Scraper</title>

        <style>

            body {
                font-family: Arial;
                background: #f3f4f6;
                padding: 50px;
            }

            .container {
                max-width: 650px;
                margin: auto;
                background: white;
                padding: 35px;
                border-radius: 12px;
                box-shadow: 0 4px 15px rgba(0,0,0,0.1);
            }

            input {
                width: 65%;
                padding: 12px;
                font-size: 16px;
            }

            button {
                padding: 12px 20px;
                background: #2563eb;
                color: white;
                border: none;
                border-radius: 5px;
                cursor: pointer;
            }

        </style>

    </head>

    <body>

        <div class="container">

            <h1>💻 Laptop Web Scraper</h1>

            <p>
                Search for laptops by brand or model.
            </p>

            <form action="/scrape" method="post">

                <input
                    name="query"
                    placeholder="Dell, Lenovo, HP..."
                    required
                >

                <button type="submit">
                    🔎 Search
                </button>

            </form>

        </div>

    </body>

    </html>
    """


# ============================================================
# SEARCH / SCRAPE
# ============================================================

@app.route("/scrape", methods=["POST"])
def scrape():

    query = request.form.get(
        "query",
        ""
    ).strip().lower()


    # --------------------------------------------------------
    # FILTER LAPTOP DATA
    # --------------------------------------------------------

    products = []

    for laptop in laptops:

        searchable_text = (
            laptop["title"]
            + " "
            + laptop["brand"]
            + " "
            + laptop["processor"]
            + " "
            + laptop["ram"]
            + " "
            + laptop["storage"]
        ).lower()

        if query in searchable_text:

            products.append(laptop)


    # --------------------------------------------------------
    # NO RESULTS
    # --------------------------------------------------------

    if not products:

        return f"""

        <h2>❌ No laptops found</h2>

        <p>
            Search:
            <b>{query}</b>
        </p>

        <p>
            Try:
            <b>Dell</b>,
            <b>Lenovo</b>,
            <b>HP</b>,
            <b>Acer</b>,
            or
            <b>ASUS</b>.
        </p>

        <a href="/">
            ← Search Again
        </a>

        """


    # --------------------------------------------------------
    # CREATE DATAFRAME
    # --------------------------------------------------------

    df = pd.DataFrame(products)


    # --------------------------------------------------------
    # SAVE CSV
    # --------------------------------------------------------

    df.to_csv(
        CSV_FILE,
        index=False
    )


    # --------------------------------------------------------
    # CREATE HTML TABLE
    # --------------------------------------------------------

    table = """

    <table border="1"
           cellpadding="10"
           style="
               border-collapse:collapse;
               width:100%;
           ">

        <tr style="
            background:#2563eb;
            color:white;
        ">

            <th>Model</th>
            <th>Brand</th>
            <th>Price</th>
            <th>Processor</th>
            <th>RAM</th>
            <th>Storage</th>
            <th>Rating</th>

        </tr>

    """


    for laptop in products:

        table += f"""

        <tr>

            <td>
                <b>{laptop["title"]}</b>
            </td>

            <td>
                {laptop["brand"]}
            </td>

            <td>
                {laptop["price"]}
            </td>

            <td>
                {laptop["processor"]}
            </td>

            <td>
                {laptop["ram"]}
            </td>

            <td>
                {laptop["storage"]}
            </td>

            <td>
                ⭐ {laptop["rating"]}
            </td>

        </tr>

        """


    table += "</table>"


    # --------------------------------------------------------
    # RESULT PAGE
    # --------------------------------------------------------

    return f"""

    <!DOCTYPE html>

    <html>

    <head>

        <title>Laptop Results</title>

        <style>

            body {{
                font-family:Arial;
                padding:40px;
                background:#f5f5f5;
            }}

            .container {{
                background:white;
                padding:30px;
                border-radius:10px;
            }}

            table {{
                margin-top:20px;
            }}

            td, th {{
                padding:10px;
            }}

            .download {{
                display:inline-block;
                margin-top:20px;
                padding:12px 18px;
                background:#16a34a;
                color:white;
                text-decoration:none;
                border-radius:5px;
            }}

        </style>

    </head>

    <body>

        <div class="container">

            <h2>💻 Laptop Search Results</h2>

            <p>
                Search:
                <b>{query}</b>
            </p>

            <p>
                ✅ Found
                <b>{len(products)}</b>
                laptops
            </p>

            {table}

            <br>

            <a
                class="download"
                href="/download"
            >
                ⬇️ Download CSV
            </a>

            <br><br>

            <a href="/">
                ← Search Again
            </a>

        </div>

    </body>

    </html>

    """


# ============================================================
# DOWNLOAD CSV
# ============================================================

@app.route("/download")
def download():

    return send_file(
        CSV_FILE,
        as_attachment=True,
        download_name="laptop_results.csv"
    )


# ============================================================
# NGROK
# ============================================================

ngrok.kill()

# PUT YOUR REAL NGROK TOKEN HERE
ngrok.set_auth_token(
    "auth_token"
)

public_url = ngrok.connect(5000)

print("🌐 Open this URL:")
print(public_url)


# ============================================================
# START FLASK
# ============================================================

app.run(
    host="0.0.0.0",
    port=5000
)